version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    network_mode: service:db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "scotland"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "dev"
      # You can use whatever password you like
      MYSQL_PASSWORD: "dev1234!"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
