# Generated by Django 4.2.7 on 2023-12-17 17:03

from django.db import migrations

distilleries = [
    {"name": "Aberfeldy", "latitude": "56.625191", "longitude": "-3.850199"},
    {"name": "Aberlour", "latitude": "57.467395", "longitude": "-3.229644 "},
    {"name": "AnCnoc", "latitude": "57.441751", "longitude": "-2.785295"},
    {"name": "Ardbeg", "latitude": "55.640607", "longitude": "-6.108503"},
    {"name": "Ardmore", "latitude": "57.350557", "longitude": "-2.743628"},
    {"name": "Arran", "latitude": "55.699145", "longitude": "-5.278895"},
    {"name": "Auchentoshan", "latitude": "55.922373", "longitude": "-4.439339"},
    {"name": "Auchroisk", "latitude": "57.523872", "longitude": "-2.990865"},
    {"name": "Aultmore", "latitude": "57.523872", "longitude": "-2.990865"},
    {"name": "Balblair", "latitude": "57.842735", "longitude": "-4.177749"},
    {"name": "Balmenach", "latitude": "57.325709", "longitude": "-3.533656"},
    {"name": "Belvenie", "latitude": "57.452844", "longitude": "-3.123497"},
    {"name": "Ben Nevis", "latitude": "56.834952", "longitude": "-5.073418"},
    {"name": "Benriach", "latitude": "57.608893", "longitude": "-3.282789"},
    {"name": "Benrinnes", "latitude": "57.443508", "longitude": "-3.237839"},
    {"name": "Benromach", "latitude": "57.613737", "longitude": "-3.619764"},
    {"name": "Bladnoch", "latitude": "54.858193", "longitude": "-4.458949"},
    {"name": "Blair Athol", "latitude": "56.698063", "longitude": "-3.718544"},
    {"name": "Bowmore", "latitude": "55.756024", "longitude": "-6.283806"},
    {"name": "Bruichladdich", "latitude": "55.768473", "longitude": "-6.359365"},
    {"name": "Bunnahabhain", "latitude": "55.882475", "longitude": "-6.123657"},
    {"name": "Caol Ila", "latitude": "55.854804", "longitude": "-6.109369"},
    {"name": "Cardhu", "latitude": "57.470774", "longitude": "-3.355645"},
    {"name": "Clynelish", "latitude": "58.013647", "longitude": "-3.859208"},
    {"name": "Craigallechie", "latitude": "57.488911", "longitude": "-3.187328"},
    {"name": "Craigganmore", "latitude": "57.410031", "longitude": "-3.389855"},
    {"name": "Dailuaine", "latitude": "57.452918", "longitude": "-3.276155"},
    {"name": "Dalmore", "latitude": "57.688561", "longitude": "-4.239120"},
    {"name": "Dalwhinnie", "latitude": "56.938563", "longitude": "-4.242293"},
    {"name": "Deanston", "latitude": "56.189376", "longitude": "-4.071064"},
    {"name": "Dufftown", "latitude": "57.438068", "longitude": "-3.128374"},
    {"name": "Edradour", "latitude": "56.701543", "longitude": "-3.700736"},
    {"name": "Glen Elgin", "latitude": "57.632641", "longitude": "-3.297193"},
    {"name": "Glen Garioch", "latitude": "57.338432", "longitude": "-2.316943"},
    {"name": "Glen Grant", "latitude": "57.530463", "longitude": "-3.210557"},
    {"name": "Glen Keith", "latitude": "57.523872", "longitude": "-2.990865"},
    {"name": "Glen Moray", "latitude": "57.643642", "longitude": "-3.344829"},
    {"name": "Glen Ord", "latitude": "57.523564", "longitude": "-4.476185"},
    {"name": "Glen Scotia", "latitude": "55.429810", "longitude": "-5.603737"},
    {"name": "Glen Spey", "latitude": "57.526625", "longitude": "-3.207925"},
    {"name": "Glenallachie", "latitude": "57.455475", "longitude": "-3.226744"},
    {"name": "Glendronach", "latitude": "57.492920", "longitude": "-2.648927"},
    {"name": "Glendullan", "latitude": "57.448042", "longitude": "-3.118017"},
    {"name": "Glenfarclas", "latitude": "57.426884", "longitude": "-3.318049"},
    {"name": "Glenfiddich", "latitude": "57.452844", "longitude": "-3.123497"},
    {"name": "Glengoyne", "latitude": "56.015002", "longitude": "-4.362706"},
    {"name": "Glenkinchie", "latitude": "55.890117", "longitude": "-2.890845"},
    {"name": "Glenlivet", "latitude": "57.342405", "longitude": "-3.338116"},
    {"name": "Glenlossie", "latitude": "57.632641", "longitude": "-3.297193"},
    {"name": "Glenmorangie", "latitude": "57.823585", "longitude": "-4.076735"},
    {"name": "Glenrothes", "latitude": "57.526877", "longitude": "-3.209770"},
    {"name": "Glenturret", "latitude": "56.390603", "longitude": "-3.854194"},
    {"name": "Highland Park", "latitude": "58.966865", "longitude": "-2.9524375"},
    {"name": "Inchgower", "latitude": "57.661944", "longitude": "-2.963520"},
    {"name": "Jura", "latitude": "55.833006", "longitude": "-5.951428"},
    {"name": "Knochando", "latitude": "57.457246", "longitude": "-3.343810"},
    {"name": "Lagavulin", "latitude": "55.635614", "longitude": "-6.125946"},
    {"name": "Laphroig", "latitude": "55.629569", "longitude": "-6.153129"},
    {"name": "Linkwood", "latitude": "57.632641", "longitude": "-3.297193"},
    {"name": "Loch Lomond", "latitude": "55.994260", "longitude": "-4.576973"},
    {"name": "Longmorn", "latitude": "57.632641", "longitude": "-3.297193"},
    {"name": "Macallan", "latitude": "57.484768", "longitude": "-3.207376"},
    {"name": "Macduff", "latitude": "57.632679", "longitude": "-2.468547"},
    {"name": "Mannochmore", "latitude": "57.632641", "longitude": "-3.297193"},
    {"name": "Miltonduff", "latitude": "57.632641", "longitude": "-3.297193"},
    {"name": "Mortlach", "latitude": "57.443993", "longitude": "-3.118727"},
    {"name": "Oban", "latitude": "56.415259", "longitude": "-5.471833"},
    {"name": "Old Fettercairn", "latitude": "56.846626", "longitude": "-2.479332"},
    {"name": "Old Pulteney", "latitude": "58.434884", "longitude": "-3.085261"},
    {"name": "Royal Brackla", "latitude": "57.537610", "longitude": "-3.905230"},
    {"name": "Royal Lochnagar", "latitude": "57.034488", "longitude": "-3.218602"},
    {"name": "Scapa", "latitude": "58.5747", "longitude": " -2.59594 "},
    {"name": "Speyburn", "latitude": "57.547057", "longitude": "-3.222469"},
    {"name": "Speyside", "latitude": "57.080387", "longitude": "-4.002174"},
    {"name": "Springbank", "latitude": "55.429001", "longitude": "-5.600659"},
    {"name": "Strathisla", "latitude": "57.523872", "longitude": "-2.990865"},
    {"name": "Strathmill", "latitude": "57.540974", "longitude": "-2.959656"},
    {"name": "Talisker", "latitude": "57.301051", "longitude": "-6.352166"},
    {"name": "Tamdhu", "latitude": "57.458906", "longitude": "-3.348205"},
    {"name": "Tamnavulin", "latitude": "57.318711", "longitude": "-3.310355"},
    {"name": "Teaninich", "latitude": "57.691688", "longitude": "-4.2605172"},
    {"name": "Tobermory", "latitude": "56.620806", "longitude": "-6.069530"},
    {"name": "Tomatin", "latitude": "57.341101", "longitude": "-4.010031"},
    {"name": "Tomintoul", "latitude": "57.312680", "longitude": "-3.411083"},
    {"name": "Tormore", "latitude": "57.397107", "longitude": "-3.412996"},
    {"name": "Tullibardine", "latitude": "56.259296", "longitude": "-3.782289"},
]


def add_distilleries(apps):
    distillery_model = apps.get_model("app", "Distillery")
    for distillery in distilleries:
        d = distillery_model(**distillery)
        d.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_distilleries),
    ]
